# Generated by Django 4.2.10 on 2025-07-09 07:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Reference to the order ID in the Order Management system. Format: ORD-{tenant}-{year}-{sequential_number}",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50)),
                (
                    "reference_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "place_of_supply",
                    models.CharField(
                        choices=[
                            (
                                "Andaman and Nicobar Islands",
                                "Andaman and Nicobar Islands",
                            ),
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Arunachal Pradesh", "Arunachal Pradesh"),
                            ("Assam", "Assam"),
                            ("Bihar", "Bihar"),
                            ("Chandigarh", "Chandigarh"),
                            ("Chhattisgarh", "Chhattisgarh"),
                            (
                                "Dadra and Nagar Haveli and Daman and Diu",
                                "Dadra and Nagar Haveli and Daman and Diu",
                            ),
                            ("Delhi", "Delhi"),
                            ("Goa", "Goa"),
                            ("Gujarat", "Gujarat"),
                            ("Haryana", "Haryana"),
                            ("Himachal Pradesh", "Himachal Pradesh"),
                            ("Jammu and Kashmir", "Jammu and Kashmir"),
                            ("Jharkhand", "Jharkhand"),
                            ("Karnataka", "Karnataka"),
                            ("Kerala", "Kerala"),
                            ("Ladakh", "Ladakh"),
                            ("Lakshadweep", "Lakshadweep"),
                            ("Madhya Pradesh", "Madhya Pradesh"),
                            ("Maharashtra", "Maharashtra"),
                            ("Manipur", "Manipur"),
                            ("Meghalaya", "Meghalaya"),
                            ("Mizoram", "Mizoram"),
                            ("Nagaland", "Nagaland"),
                            ("Odisha", "Odisha"),
                            ("Puducherry", "Puducherry"),
                            ("Punjab", "Punjab"),
                            ("Rajasthan", "Rajasthan"),
                            ("Sikkim", "Sikkim"),
                            ("Tamil Nadu", "Tamil Nadu"),
                            ("Telangana", "Telangana"),
                            ("Tripura", "Tripura"),
                            ("Uttar Pradesh", "Uttar Pradesh"),
                            ("Uttarakhand", "Uttarakhand"),
                            ("West Bengal", "West Bengal"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "gst_treatment",
                    models.CharField(
                        choices=[
                            ("BUSINESS_GST", "Business GST"),
                            ("CONSUMER", "Consumer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("gst_no", models.CharField(blank=True, max_length=15, null=True)),
                ("template_id", models.IntegerField(default=1)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "payment_terms",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "payment_terms_label",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("is_discount_before_tax", models.BooleanField(default=True)),
                (
                    "discount_type",
                    models.CharField(default="invoice_level", max_length=50),
                ),
                ("is_inclusive_tax", models.BooleanField(default=False)),
                (
                    "other_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("line_items", models.JSONField(default=list)),
                ("allow_partial_payments", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "terms",
                    models.TextField(blank=True, default="Terms & Conditions apply"),
                ),
                (
                    "invoice_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("TAX", "Tax"),
                            ("PROFORMA", "Proforma"),
                            ("EXPENSE", "Expense"),
                        ],
                        default="TAX",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                ("invoice_url", models.URLField(blank=True, max_length=512, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="The account associated with this invoice. Can be null for certain invoice types.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="customers.account",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="The contact associated with this invoice. Optional but recommended.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="customers.contact",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_status", "CANCELLED"), _negated=True),
                fields=("invoice_number",),
                name="unique_invoice_number_if_not_cancelled",
            ),
        ),
    ]
