# Generated by Django 4.2.10 on 2025-07-28 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0004_rule_rulecondition_ruleoutcome_and_more"),
        ("products", "0006_productzonerestriction"),
        ("customers", "0007_alter_address_country_alter_orderaddress_country"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "product_sku",
                    models.CharField(
                        db_index=True, help_text="Product SKU/code", max_length=100
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Product name at time of invoice", max_length=255
                    ),
                ),
                ("quantity", models.PositiveIntegerField(help_text="Quantity ordered")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit at time of invoice",
                        max_digits=12,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price for this line item (unit_price × quantity)",
                        max_digits=12,
                    ),
                ),
                (
                    "hsn_sac_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="HSN/SAC code for the product",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "item_order",
                    models.PositiveIntegerField(help_text="Order of the item"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the item", null=True
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        blank=True,
                        choices=[("PERCENTAGE", "Percentage"), ("AMOUNT", "Amount")],
                        db_index=True,
                        help_text="Discount type for the order",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Discount percentage for this line item",
                        max_digits=5,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Discount amount for this line item",
                        max_digits=12,
                    ),
                ),
                (
                    "uom_symbol",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement symbol for this line item",
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Item",
                "verbose_name_plural": "Invoice Items",
            },
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="date",
            new_name="issue_date",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="grand_total",
            new_name="subtotal_amount",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="other_charges",
            new_name="tax_amount",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="sub_total",
            new_name="total_amount",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="gst_no",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="line_items",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="total_tax_amount",
        ),
        migrations.AddField(
            model_name="invoice",
            name="account_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the customer account. Null for guest orders.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="ack_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="amount_due",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Amount due for this order",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Amount paid for this order",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_address",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the billing address for this order",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_billing_orders",
                to="customers.orderaddress",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="contact_person_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the contact person. May be null for guest checkouts or consumer orders.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount percentage for the order",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="irn",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_reverse_charge_applicable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="recipient_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores recipient information including name, contact, and preferences",
                verbose_name="Recipient Details",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the shipping address for this order",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_shipping_orders",
                to="customers.orderaddress",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="signed_qr_code",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount amount for the order",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("PERCENTAGE", "Percentage"), ("AMOUNT", "Amount")],
                db_index=True,
                help_text="Discount type for the order",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("PROFORMA", "Proforma"),
                    ("SALES_RECEIPT", "Sales Receipt"),
                    ("RECURRING", "Recurring"),
                ],
                default="STANDARD",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="place_of_supply",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="InvoiceItemTax",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "tax_code",
                    models.CharField(help_text="Tax code for this tax", max_length=50),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tax rate for this tax",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tax amount for this tax",
                        max_digits=12,
                    ),
                ),
                (
                    "invoice_item",
                    models.ForeignKey(
                        help_text="The invoice item this tax belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="invoices.invoiceitem",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_item_taxes",
                        to="pricing.taxrate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Item Tax",
                "verbose_name_plural": "Invoice Item Taxes",
            },
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                help_text="The invoice this item belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="product",
            field=models.ForeignKey(
                help_text="The product this item belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_items",
                to="products.product",
            ),
        ),
    ]
