# Generated by Django 4.2.10 on 2025-07-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0004_rule_rulecondition_ruleoutcome_and_more"),
        ("invoices", "0002_invoiceitem_rename_date_invoice_issue_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="responsible_person",
            field=models.BigIntegerField(
                help_text="User ID of the person who is responsible for the order.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="selling_channel",
            field=models.ForeignKey(
                blank=True,
                help_text="Selling channel for the order",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="pricing.sellingchannel",
            ),
        ),
    ]
