# Generated by Django 4.2.10 on 2025-07-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_invoice_responsible_person_invoice_selling_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="same_as_shipping",
            field=models.BooleanField(
                default=False,
                help_text="Is the billing address the same as the shipping address?",
            ),
        ),
    ]
