# Generated by Django 4.2.10 on 2025-07-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0018_remove_order_shipping_method_id_and_more"),
        ("invoices", "0004_invoice_same_as_shipping"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceOrder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="The invoice in this relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_orders",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The order in this relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_invoices",
                        to="order_management.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice order relationship",
                "verbose_name_plural": "invoice order relationships",
                "unique_together": {("invoice", "order")},
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="orders",
            field=models.ManyToManyField(
                blank=True,
                help_text="Orders associated with this invoice",
                related_name="invoices",
                through="invoices.InvoiceOrder",
                to="order_management.order",
            ),
        ),
    ]
