# Generated by Django 4.2.10 on 2025-07-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0005_invoiceorder_invoice_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="fulfillment_type",
            field=models.CharField(
                blank=True,
                help_text="Fullfillment type for the order",
                max_length=50,
                null=True,
            ),
        ),
    ]
