# Generated by Django 4.2.10 on 2025-07-30 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0018_remove_order_shipping_method_id_and_more"),
        ("invoices", "0006_invoice_fulfillment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pickup_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores pickup location, date, time slot, and instructions",
                verbose_name="Pickup Details",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="storepickup",
            field=models.ForeignKey(
                blank=True,
                help_text="Store pickup for the order",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="order_management.storepickup",
            ),
        ),
    ]
