# Generated by Django 4.2.10 on 2025-07-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment_method", "0002_rename_foreign_key_fields"),
        ("invoices", "0007_invoice_pickup_details_invoice_storepickup"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoicePaymentMethod",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="The invoice in this relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_payment_methods",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        help_text="The payment method in this relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_method_invoices",
                        to="payment_method.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Payment Method",
                "verbose_name_plural": "Invoice Payment Methods",
                "unique_together": {("invoice", "payment_method")},
            },
        ),
    ]
