# Generated by Django 4.2.10 on 2025-08-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0008_invoicepaymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="config_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="A snapshot of the invoice configuration at the time of creation.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="InvoiceCounter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "config_assignment_id",
                    models.PositiveIntegerField(
                        help_text="The ID of the configuration assignment (response.id from the API)."
                    ),
                ),
                (
                    "reset_period_key",
                    models.CharField(default="all_time", max_length=20),
                ),
                ("last_sequence", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Invoice Counter",
                "verbose_name_plural": "Invoice Counters",
                "unique_together": {("config_assignment_id", "reset_period_key")},
            },
        ),
    ]
