# Generated by Django 4.2.10 on 2025-08-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0009_invoice_config_snapshot_invoicecounter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Unpaid"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                    ("PARTIALLY_PAID", "Partially Paid"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
    ]
