# Generated by Django 4.2.10 on 2025-07-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxrate",
            name="tax_regions",
        ),
        migrations.AddField(
            model_name="taxrate",
            name="tax_region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="TaxRegion",
        ),
    ]
