# Generated by Django 4.2.10 on 2025-07-23 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0002_remove_taxrate_tax_regions_taxrate_tax_region_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taxrate",
            options={"ordering": ["tax_type_code"]},
        ),
        migrations.AlterModelOptions(
            name="taxrateprofile",
            options={"ordering": ["profile_name"]},
        ),
        migrations.RenameField(
            model_name="taxrate",
            old_name="tax_code",
            new_name="rate_name",
        ),
        migrations.RenameField(
            model_name="taxrate",
            old_name="tax_percentage",
            new_name="rate_percentage",
        ),
        migrations.AlterUniqueTogether(
            name="taxrateprofile",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="category_id",
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="description",
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="price_from",
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="price_to",
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="tax_region",
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="tax_type",
        ),
        migrations.AddField(
            model_name="taxrate",
            name="country_code",
            field=models.CharField(db_index=True, default="IN", max_length=2),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="custom_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="effective_from",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taxrate",
            name="effective_to",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="tax_type_code",
            field=models.CharField(
                db_index=True, default="default value", max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taxrateprofile",
            name="country_code",
            field=models.CharField(
                db_index=True,
                default="IN",
                help_text="ISO 3166-1 alpha-2 country code",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="taxrateprofile",
            name="custom_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taxrateprofile",
            name="profile_name",
            field=models.CharField(
                db_index=True,
                default="yash",
                help_text="Unique name for the tax profile, e.g., 'Indian Garments Conditional Tax Profile'",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="company_id",
            field=models.BigIntegerField(
                db_index=True,
                default=1,
                editable=False,
                help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
            ),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="created_by",
            field=models.BigIntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="updated_by",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="taxrateprofile",
            name="company_id",
            field=models.BigIntegerField(
                db_index=True,
                default=1,
                editable=False,
                help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
            ),
        ),
        migrations.AlterField(
            model_name="taxrateprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="taxrateprofile",
            name="created_by",
            field=models.BigIntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="taxrateprofile",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="taxrateprofile",
            name="updated_by",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name="taxrate",
            index=models.Index(
                fields=["tax_type_code", "country_code"],
                name="pricing_tax_tax_typ_2591ae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxrate",
            index=models.Index(
                fields=["country_code", "is_active"],
                name="pricing_tax_country_e3c22a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxrate",
            index=models.Index(
                fields=["effective_from", "effective_to"],
                name="pricing_tax_effecti_f987c2_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="taxrateprofile",
            name="code",
        ),
        migrations.RemoveField(
            model_name="taxrateprofile",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="taxrateprofile",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="taxrateprofile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="taxrateprofile",
            name="tax_rates",
        ),
    ]
