# Generated by Django 4.2.10 on 2025-08-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0004_rule_rulecondition_ruleoutcome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxrateprofile",
            name="profile_name",
            field=models.CharField(
                db_index=True,
                help_text="Unique name for the tax profile, e.g., 'Indian Garments Conditional Tax Profile'",
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="taxrateprofile",
            constraint=models.UniqueConstraint(
                fields=("client_id", "profile_name"), name="unique_client_profile_name"
            ),
        ),
    ]
