# Generated by Django 4.2.10 on 2025-08-07 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "receipts",
            "0002_audittrail_receipt_original_receipt_receipt_source_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tdsadjustments",
            name="receipt",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tds_adjustments",
                to="receipts.receipt",
            ),
            preserve_default=False,
        ),
    ]
