# Generated by Django 4.2.20 on 2025-06-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                ("slug", models.SlugField(default="home", unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "meta_description",
                    models.TextField(blank=True, help_text="SEO meta description"),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="SEO keywords, comma separated",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Landing Page",
                "verbose_name_plural": "Landing Pages",
                "unique_together": {("client_id", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("HERO_CAROUSEL", "Hero Carousel"),
                            ("BANNER_AD_GRID", "Banner Ad Grid"),
                            ("RECENTLY_VIEWED", "Recently Viewed Products"),
                            ("FEATURED_PRODUCTS", "Featured Products"),
                            ("TEXT_CONTENT", "Text Content"),
                            ("NEWSLETTER_SIGNUP", "Newsletter Signup"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Internal title for admin reference",
                        max_length=200,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON configuration for this block",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="pages.landingpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Block",
                "verbose_name_plural": "Content Blocks",
                "ordering": ["page", "order"],
                "unique_together": {("client_id", "page", "order")},
            },
        ),
    ]
