# Generated by Django 4.2.20 on 2025-06-06 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.BigIntegerField(null=True, blank=True)),
                ("updated_by_id", models.BigIntegerField(null=True, blank=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("symbol", models.CharField(max_length=5)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "exchange_rate_to_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=1.0,
                        help_text="Exchange rate to USD",
                        max_digits=14,
                    ),
                ),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                ("company_id", models.BigIntegerField(default=1, editable=False)),
            ],
            options={
                "verbose_name_plural": "Currencies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.BigIntegerField(null=True, blank=True)),
                ("updated_by_id", models.BigIntegerField(null=True, blank=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("iso_code", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("flag_url", models.URLField(blank=True, null=True)),
                ("phone_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "iso_code_3",
                    models.CharField(blank=True, max_length=3, null=True, unique=True),
                ),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                ("company_id", models.BigIntegerField(default=1, editable=False)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
    ]
