# Generated by Django 4.2.10 on 2025-07-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorePickup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="store name")),
                (
                    "contact_person",
                    models.CharField(max_length=255, verbose_name="contact person"),
                ),
                (
                    "contact_number",
                    models.CharField(max_length=20, verbose_name="contact number"),
                ),
                (
                    "address_line1",
                    models.CharField(max_length=255, verbose_name="address line 1"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="address line 2",
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="country")),
                ("state", models.CharField(max_length=100, verbose_name="state")),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                ("pincode", models.CharField(max_length=20, verbose_name="pincode")),
                (
                    "google_place_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Google Place ID",
                    ),
                ),
                (
                    "operating_hours",
                    models.JSONField(
                        default=dict,
                        help_text='Format: {"monday": {"open": "09:00", "close": "18:00", "is_open": true}, ...}',
                        verbose_name="operating hours",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "store pickup",
                "verbose_name_plural": "store pickups",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="order_manag_name_d7e79d_idx"),
                    models.Index(fields=["city"], name="order_manag_city_084b7e_idx"),
                    models.Index(
                        fields=["is_active"], name="order_manag_is_acti_fdf3a3_idx"
                    ),
                ],
            },
        ),
    ]
