# Generated by Django 4.2.10 on 2025-07-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0002_storepickup"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="slot name")),
                ("start_time", models.TimeField(verbose_name="start time")),
                ("end_time", models.TimeField(verbose_name="end time")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "time slot",
                "verbose_name_plural": "time slots",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the shipping method (e.g., Standard, Express, Overnight)",
                        max_length=100,
                        verbose_name="method name",
                    ),
                ),
                (
                    "min_delivery_days",
                    models.PositiveSmallIntegerField(
                        help_text="Minimum estimated delivery time in days",
                        verbose_name="minimum delivery days",
                    ),
                ),
                (
                    "max_delivery_days",
                    models.PositiveSmallIntegerField(
                        help_text="Maximum estimated delivery time in days",
                        verbose_name="maximum delivery days",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this shipping method is active and available for selection",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "shipping method",
                "verbose_name_plural": "shipping methods",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="order_manag_name_90e94b_idx"),
                    models.Index(
                        fields=["is_active"], name="order_manag_is_acti_9018ca_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="shippingmethod",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("max_delivery_days__gte", models.F("min_delivery_days"))
                ),
                name="max_delivery_not_less_than_min",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingmethod",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_shipping_method_name_per_tenant"
            ),
        ),
    ]
