# Generated by Django 4.2.10 on 2025-07-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0003_timeslot_shippingmethod_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconfiguration",
            name="checkout_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Checkout configuration settings including guest checkout, order values, and delivery preferences",
            ),
        ),
    ]
