# Generated by Django 4.2.10 on 2025-07-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_productvisibility"),
        ("pricing", "0001_initial"),
        ("customers", "0005_orderaddress"),
        ("order_management", "0005_customergroupsellingchannelstorepickup_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_amount",
        ),
        migrations.AddField(
            model_name="order",
            name="account_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the customer account. Null for guest orders.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="contact_person_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the contact person. May be null for guest checkouts or consumer orders.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_level",
            field=models.CharField(
                choices=[("ORDER_LEVEL", "Order Level"), ("ITEM_LEVEL", "Item Level")],
                db_index=True,
                default="ORDER_LEVEL",
                help_text="Discount level for the order",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount percentage for the order",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("PERCENTAGE", "Percentage"), ("AMOUNT", "Amount")],
                db_index=True,
                help_text="Discount type for the order",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the order was created",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="other_charges",
            field=models.DecimalField(
                decimal_places=2, default=0.0, help_text="Other charges", max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="selling_channel",
            field=models.ForeignKey(
                blank=True,
                help_text="Selling channel for the order",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="pricing.sellingchannel",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the item", null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount amount for this line item",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount percentage for this line item",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("PERCENTAGE", "Percentage"), ("AMOUNT", "Amount")],
                db_index=True,
                help_text="Discount type for the order",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="hsn_sac_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HSN/SAC code for the product",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item_order",
            field=models.PositiveIntegerField(default=1, help_text="Order of the item"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_id",
            field=models.ForeignKey(
                default=1,
                help_text="The product this item belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="products.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_address",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the billing address for this order",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_orders",
                to="customers.orderaddress",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount amount for the order",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the shipping address for this order",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipping_orders",
                to="customers.orderaddress",
            ),
        ),
        migrations.CreateModel(
            name="OrderItemTax",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "tax_code",
                    models.CharField(help_text="Tax code for this tax", max_length=50),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tax rate for this tax",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tax amount for this tax",
                        max_digits=12,
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        help_text="The order item this tax belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="order_management.orderitem",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item_taxes",
                        to="pricing.taxrate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item Tax",
                "verbose_name_plural": "Order Item Taxes",
            },
        ),
    ]
