# Generated by Django 4.2.10 on 2025-07-21 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "order_management",
            "0006_remove_order_shipping_amount_order_account_name_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="product_id",
            new_name="product",
        ),
    ]
