# Generated by Django 4.2.10 on 2025-07-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0007_rename_product_id_orderitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="fulfillment_details",
        ),
        migrations.AddField(
            model_name="order",
            name="fulfillment_type",
            field=models.CharField(
                blank=True,
                help_text="Fullfillment type for the order",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="responsible_person",
            field=models.BigIntegerField(
                help_text="User ID of the person who is responsible for the order.",
                null=True,
            ),
        ),
    ]
