# Generated by Django 4.2.10 on 2025-07-24 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0006_alter_orderaddress_country"),
        ("order_management", "0008_remove_order_fulfillment_details_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutConfiguration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "allow_guest_checkout",
                    models.BooleanField(
                        default=True,
                        help_text="Allow customers to checkout without creating an account",
                    ),
                ),
                (
                    "min_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum order amount required to place an order",
                        max_digits=10,
                    ),
                ),
                (
                    "allow_user_select_shipping",
                    models.BooleanField(
                        default=True,
                        help_text="Allow users to select their preferred shipping method",
                    ),
                ),
                (
                    "enable_in_store_pickup",
                    models.BooleanField(
                        default=False, help_text="Enable in-store pickup option"
                    ),
                ),
                (
                    "pickup_method_label",
                    models.CharField(
                        default="In-Store Pickup",
                        help_text="Display name for the in-store pickup option",
                        max_length=100,
                    ),
                ),
                (
                    "enable_delivery_prefs",
                    models.BooleanField(
                        default=False,
                        help_text="Enable delivery preferences during checkout",
                    ),
                ),
                (
                    "enable_preferred_date",
                    models.BooleanField(
                        default=False,
                        help_text="Allow customers to select preferred delivery date",
                    ),
                ),
                (
                    "enable_time_slots",
                    models.BooleanField(
                        default=False,
                        help_text="Enable time slot selection for delivery/pickup",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR",
                        help_text="Default currency code (ISO 4217) for the store",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "verbose_name": "Checkout Configuration",
                "verbose_name_plural": "Checkout Configurations",
                "db_table": "order_management_checkout_configuration",
                "ordering": ["id"],
            },
        ),
        migrations.RemoveField(
            model_name="tenantconfiguration",
            name="checkout_config",
        ),
        migrations.CreateModel(
            name="CustomerGroupSellingChannelCheckoutConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this relationship is active",
                    ),
                ),
                (
                    "checkout_config",
                    models.ForeignKey(
                        help_text="Reference to the CheckoutConfiguration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_group_selling_channel_relationships",
                        to="order_management.checkoutconfiguration",
                    ),
                ),
                (
                    "customer_group_selling_channel",
                    models.ForeignKey(
                        help_text="Reference to the CustomerGroupSellingChannel relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_config_relationships",
                        to="customers.customergroupsellingchannel",
                    ),
                ),
            ],
            options={
                "db_table": "order_management_checkout_config_assignments",
                "ordering": ["customer_group_selling_channel", "checkout_config__id"],
            },
        ),
        migrations.AddField(
            model_name="checkoutconfiguration",
            name="customer_group_selling_channels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Customer group and selling channel combinations that use this checkout configuration",
                related_name="checkout_configurations",
                through="order_management.CustomerGroupSellingChannelCheckoutConfig",
                to="customers.customergroupsellingchannel",
            ),
        ),
        migrations.AddIndex(
            model_name="customergroupsellingchannelcheckoutconfig",
            index=models.Index(
                fields=["customer_group_selling_channel", "is_active"],
                name="idx_cgsccc_cgsc_act",
            ),
        ),
        migrations.AddIndex(
            model_name="customergroupsellingchannelcheckoutconfig",
            index=models.Index(
                fields=["checkout_config", "is_active"], name="idx_cgsccc_cc_act"
            ),
        ),
        migrations.AddIndex(
            model_name="customergroupsellingchannelcheckoutconfig",
            index=models.Index(
                fields=[
                    "customer_group_selling_channel",
                    "checkout_config",
                    "is_active",
                ],
                name="idx_cgsccc_all",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customergroupsellingchannelcheckoutconfig",
            unique_together={("customer_group_selling_channel", "checkout_config")},
        ),
    ]
