# Generated by Django 4.2.10 on 2025-07-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0006_alter_orderaddress_country"),
        ("order_management", "0010_create_default_checkout_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutconfiguration",
            name="customer_group_selling_channels",
        ),
        migrations.AddField(
            model_name="checkoutconfiguration",
            name="customer_group_selling_channel",
            field=models.OneToOneField(
                blank=True,
                help_text="Customer group and selling channel combination for this checkout configuration",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkout_configuration",
                to="customers.customergroupsellingchannel",
            ),
        ),
        migrations.DeleteModel(
            name="CustomerGroupSellingChannelCheckoutConfig",
        ),
    ]
