# Generated by Django 4.2.10 on 2025-07-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "order_management",
            "0011_remove_checkoutconfiguration_customer_group_selling_channels_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutconfiguration",
            name="enable_in_store_pickup",
        ),
        migrations.AddField(
            model_name="checkoutconfiguration",
            name="fulfillment_type",
            field=models.CharField(
                choices=[
                    ("delivery", "Delivery"),
                    ("store_pickup", "Store Pickup"),
                    ("both", "Delivery and Store Pickup"),
                ],
                default="both",
                help_text="Select fulfillment options: Delivery, Store Pickup, or Both",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="checkoutconfiguration",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Is this checkout configuration active?"
            ),
        ),
    ]
