# Generated by Django 4.2.10 on 2025-07-24 17:09

from django.db import migrations, models
import django.db.models.deletion


def create_default_ui_template_settings(apps, schema_editor):
    UITemplateSettings = apps.get_model('order_management', 'UITemplateSettings')
    UITemplateSettings.objects.create(
        checkout_layout="layout1",
        pdp_layout_style="classic",
        product_card_style="card1",
        is_active=True
    )

class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0006_alter_orderaddress_country"),
        (
            "order_management",
            "0012_remove_checkoutconfiguration_enable_in_store_pickup_and_more",
        ),
    ]

    operations = [
        # ... your existing operations ...
        migrations.RemoveField(
            model_name="tenantconfiguration",
            name="ui_template_settings",
        ),
        migrations.CreateModel(
            name="UITemplateSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "checkout_layout",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Checkout page layout style",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "pdp_layout_style",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Product detail page layout style",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "product_card_style",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Product card style",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Is this UI template setting active?",
                    ),
                ),
                (
                    "customer_group_selling_channel",
                    models.OneToOneField(
                        blank=True,
                        help_text="Customer group and selling channel combination for this UI template setting",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_template_settings",
                        to="customers.customergroupsellingchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI Template Setting",
                "verbose_name_plural": "UI Template Settings",
                "db_table": "order_management_ui_template_settings",
                "indexes": [
                    models.Index(
                        fields=["checkout_layout"],
                        name="order_manag_checkou_45bf9f_idx",
                    ),
                    models.Index(
                        fields=["pdp_layout_style"],
                        name="order_manag_pdp_lay_c6de3c_idx",
                    ),
                    models.Index(
                        fields=["product_card_style"],
                        name="order_manag_product_888e86_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="order_manag_is_acti_b9c2d6_idx"
                    ),
                    models.Index(
                        fields=["customer_group_selling_channel"],
                        name="order_manag_custome_a52f5b_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(create_default_ui_template_settings),
    ]
