# Generated by Django 4.2.10 on 2025-07-25 05:36

from django.db import migrations, models
import django.db.models.deletion

def create_default_feature_toggles(apps, schema_editor):
    FeatureToggleSettings = apps.get_model('order_management', 'FeatureToggleSettings')
    FeatureToggleSettings.objects.create(
        wallet_enabled=False,
        loyalty_enabled=False,
        reviews_enabled=True,
        wishlist_enabled=True,
        min_recharge_amount=None,
        max_recharge_amount=None,
        daily_transaction_limit=None,
        is_active=True,
    )

class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0006_alter_orderaddress_country"),
        (
            "order_management",
            "0013_remove_tenantconfiguration_ui_template_settings_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantconfiguration",
            name="feature_toggles",
        ),
        migrations.RemoveField(
            model_name="tenantconfiguration",
            name="loyalty_config",
        ),
        migrations.RemoveField(
            model_name="tenantconfiguration",
            name="returns_config",
        ),
        migrations.RemoveField(
            model_name="tenantconfiguration",
            name="wallet_config",
        ),
        migrations.CreateModel(
            name="FeatureToggleSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                ("wallet_enabled", models.BooleanField(db_index=True, default=False)),
                ("loyalty_enabled", models.BooleanField(db_index=True, default=False)),
                ("reviews_enabled", models.BooleanField(db_index=True, default=False)),
                ("wishlist_enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "min_recharge_amount",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        default=10.0,
                        help_text="Minimum amount for a single recharge",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_recharge_amount",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        default=10000.0,
                        help_text="Maximum amount for a single recharge",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "daily_transaction_limit",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        default=5000.0,
                        help_text="Daily transaction limit",
                        max_digits=10,
                        null=True,
                    ),
                ),

                (
                    "customer_group_selling_channel",
                    models.OneToOneField(
                        blank=True,
                        help_text="Customer group and selling channel combination for this feature toggle setting",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_toggle_settings",
                        to="customers.customergroupsellingchannel",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        db_index=True,
                        help_text="Is this feature toggle setting active?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Toggle Settings",
                "verbose_name_plural": "Feature Toggle Settings",
                "db_table": "order_management_feature_toggle_settings",
            },
        ),
        migrations.RunPython(create_default_feature_toggles, reverse_code=migrations.RunPython.noop),
    ]
