# Generated by Django 4.2.10 on 2025-07-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "order_management",
            "0014_remove_tenantconfiguration_feature_toggles_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="featuretogglesettings",
            name="default_delivery_zone",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Default delivery zone to use if not specified elsewhere.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="featuretogglesettings",
            name="kill_switch",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If enabled, disables all features for this tenant (emergency kill switch).",
            ),
        ),
    ]
