# Generated by Django 4.2.10 on 2025-07-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0016_shippingmethodzonerestriction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount_level",
        ),
        migrations.RemoveField(
            model_name="order",
            name="other_charges",
        ),
        migrations.AddField(
            model_name="order",
            name="same_as_shipping",
            field=models.BooleanField(
                default=False,
                help_text="Is the billing address the same as the shipping address?",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="uom_symbol",
            field=models.CharField(
                blank=True,
                help_text="Unit of measurement symbol for this line item",
                max_length=10,
                null=True,
            ),
        ),
    ]
