# Generated by Django 4.2.10 on 2025-07-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0017_remove_order_discount_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_method_id",
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                help_text="Shipping method selected for this order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="order_management.shippingmethod",
            ),
        ),
    ]
