# Generated by Django 4.2.10 on 2025-07-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0018_remove_order_shipping_method_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="storepickup",
            field=models.ForeignKey(
                blank=True,
                help_text="Store pickup for the order",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="order_management.storepickup",
            ),
        ),
    ]
