# Generated by Django 4.2.10 on 2025-07-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0019_order_storepickup"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="source",
            field=models.CharField(
                blank=True, help_text="Source of the order", max_length=50, null=True
            ),
        ),
    ]
