# Generated by Django 4.2.10 on 2025-07-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0020_order_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutconfiguration",
            name="fulfillment_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("delivery", "Delivery"),
                    ("store_pickup", "Store Pickup"),
                    ("both", "Delivery and Store Pickup"),
                ],
                default="both",
                help_text="Select fulfillment options: Delivery, Store Pickup, or Both",
                max_length=20,
            ),
        ),
    ]
