# Generated by Django 4.2.10 on 2025-07-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0021_alter_checkoutconfiguration_fulfillment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutconfiguration",
            name="pickup_method_label",
            field=models.CharField(
                blank=True,
                default="In-Store Pickup",
                help_text="Display name for the in-store pickup option",
                max_length=100,
            ),
        ),
    ]
