# Generated by Django 4.2.10 on 2025-08-06 07:32

from django.db import migrations, models


def set_first_record_as_default(apps, schema_editor):
    # Set first CheckoutConfiguration as default
    CheckoutConfiguration = apps.get_model('order_management', 'CheckoutConfiguration')
    first_config = CheckoutConfiguration.objects.first()
    if first_config:
        first_config.is_default = True
        first_config.save()
    
    # Set first UITemplateSettings as default
    UITemplateSettings = apps.get_model('order_management', 'UITemplateSettings')
    first_ui = UITemplateSettings.objects.first()
    if first_ui:
        first_ui.is_default = True
        first_ui.save()
    
    # Set first FeatureToggleSettings as default
    FeatureToggleSettings = apps.get_model('order_management', 'FeatureToggleSettings')
    first_feature = FeatureToggleSettings.objects.first()
    if first_feature:
        first_feature.is_default = True
        first_feature.save()


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0022_alter_checkoutconfiguration_pickup_method_label"),
    ]

    operations = [
        # First add the fields
        migrations.AddField(
            model_name="checkoutconfiguration",
            name="is_default",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Is this the default checkout configuration? Only one configuration can be default.",
            ),
        ),
        migrations.AddField(
            model_name="featuretogglesettings",
            name="is_default",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Is this the default feature toggle setting? Only one setting can be default.",
            ),
        ),
        migrations.AddField(
            model_name="uitemplatesettings",
            name="is_default",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Is this the default UI template setting? Only one setting can be default.",
            ),
        ),
        migrations.AddIndex(
            model_name="featuretogglesettings",
            index=models.Index(
                fields=["is_default"], name="order_manag_is_defa_2f7c40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uitemplatesettings",
            index=models.Index(
                fields=["is_default"], name="order_manag_is_defa_a44623_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="checkoutconfiguration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_checkout_config",
            ),
        ),
        migrations.AddConstraint(
            model_name="featuretogglesettings",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_feature_toggle",
            ),
        ),
        migrations.AddConstraint(
            model_name="uitemplatesettings",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_ui_template",
            ),
        ),
        
        # Run data migration to set first record of each model as default
        migrations.RunPython(set_first_record_as_default),
    ]
