# Generated by Django 4.2.10 on 2025-08-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0023_checkoutconfiguration_is_default_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "selling_channel",
                    models.CharField(
                        db_index=True,
                        help_text="ID of the selling channel",
                        max_length=100,
                    ),
                ),
                (
                    "customer_group_id",
                    models.BigIntegerField(
                        db_index=True, help_text="ID of the customer group"
                    ),
                ),
                (
                    "segment_id",
                    models.BigIntegerField(
                        db_index=True, help_text="ID of the segment"
                    ),
                ),
            ],
            options={
                "verbose_name": "Guest Config",
                "verbose_name_plural": "Guest Configs",
                "db_table": "order_management_guest_config",
                "indexes": [
                    models.Index(
                        fields=["selling_channel"],
                        name="order_manag_selling_6ada69_idx",
                    ),
                    models.Index(
                        fields=["customer_group_id"],
                        name="order_manag_custome_d66cee_idx",
                    ),
                    models.Index(
                        fields=["segment_id"], name="order_manag_segment_c2de1f_idx"
                    ),
                ],
                "unique_together": {
                    ("selling_channel", "customer_group_id", "segment_id")
                },
            },
        ),
    ]
