# Generated by Django 4.2.10 on 2025-08-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0024_guestconfig"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="guestconfig",
            name="order_manag_selling_6ada69_idx",
        ),
        migrations.AlterUniqueTogether(
            name="guestconfig",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="guestconfig",
            name="selling_channel_id",
            field=models.BigIntegerField(
                db_index=True, default=1, help_text="ID of the selling channel"
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="guestconfig",
            unique_together={("selling_channel_id", "customer_group_id", "segment_id")},
        ),
        migrations.AddIndex(
            model_name="guestconfig",
            index=models.Index(
                fields=["selling_channel_id"], name="order_manag_selling_8f112c_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="guestconfig",
            name="selling_channel",
        ),
    ]
