# Generated by Django 4.2.10 on 2025-07-20 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PincodeMaster",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "pincode",
                    models.CharField(
                        db_index=True,
                        help_text="6-digit Indian Pincode",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True,
                        help_text="Primary city/post office name",
                        max_length=100,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        db_index=True, help_text="District name", max_length=100
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        db_index=True, help_text="State name", max_length=100
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        db_index=True,
                        default="IN",
                        help_text="ISO 3166-1 alpha-2 country code",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pincode Master",
                "verbose_name_plural": "Pincode Master",
                "db_table": "shipping_zones_pincode_master",
                "ordering": ["pincode"],
            },
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "zone_name",
                    models.CharField(
                        db_index=True,
                        help_text="A unique, human-readable name (e.g., 'Surat Metro', 'Pune Rural')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional internal description of the zone",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable or disable the zone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Zone",
                "verbose_name_plural": "Shipping Zones",
                "db_table": "shipping_zones",
                "ordering": ["zone_name"],
            },
        ),
        migrations.CreateModel(
            name="PincodeZoneAssignment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "pincode",
                    models.OneToOneField(
                        help_text="The pincode being assigned to a zone",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_assignment",
                        to="shipping_zones.pincodemaster",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        help_text="The zone this pincode belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_pincodes",
                        to="shipping_zones.shippingzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pincode Zone Assignment",
                "verbose_name_plural": "Pincode Zone Assignments",
                "db_table": "pincode_zone_assignments",
            },
        ),
        migrations.AddIndex(
            model_name="pincodemaster",
            index=models.Index(
                fields=["pincode"], name="shipping_zo_pincode_82b388_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pincodemaster",
            index=models.Index(
                fields=["city", "state"], name="shipping_zo_city_8e5d1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pincodemaster",
            index=models.Index(
                fields=["district", "state"], name="shipping_zo_distric_366264_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pincodemaster",
            index=models.Index(fields=["state"], name="shipping_zo_state_cfd4b0_idx"),
        ),
        migrations.AddIndex(
            model_name="pincodemaster",
            index=models.Index(
                fields=["country_code"], name="shipping_zo_country_0328c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pincodezoneassignment",
            index=models.Index(
                fields=["pincode"], name="pincode_zon_pincode_9d3583_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pincodezoneassignment",
            index=models.Index(fields=["zone"], name="pincode_zon_zone_id_44fdf8_idx"),
        ),
        migrations.AddConstraint(
            model_name="pincodezoneassignment",
            constraint=models.UniqueConstraint(
                fields=("pincode", "client_id"), name="unique_pincode_per_tenant"
            ),
        ),
    ]
