# Generated by Django 4.2.10 on 2025-07-20 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_zones", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pincodezoneassignment",
            new_name="shipping_zo_pincode_a1efa7_idx",
            old_name="pincode_zon_pincode_9d3583_idx",
        ),
        migrations.RenameIndex(
            model_name="pincodezoneassignment",
            new_name="shipping_zo_zone_id_9e32fc_idx",
            old_name="pincode_zon_zone_id_44fdf8_idx",
        ),
        migrations.AlterModelTable(
            name="pincodezoneassignment",
            table="shipping_zone_pincode_assignments",
        ),
    ]
