# Generated by Django 4.2.10 on 2025-07-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_zones", "0002_rename_pincode_zon_pincode_9d3583_idx_shipping_zo_pincode_a1efa7_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pincodemaster",
            name="pincode",
            field=models.CharField(
                db_index=True, help_text="6-digit Indian Pincode", max_length=10
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pincodemaster",
            unique_together={("pincode", "city", "district")},
        ),
    ]
