# Generated by Django 4.2.10 on 2025-07-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_zones", "0004_alter_pincodemaster_pincode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pincodemaster",
            name="city",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Primary city/post office name",
                max_length=100,
                null=True,
            ),
        ),
    ]
