# Generated by Django 4.2.10 on 2025-07-09 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Primary display name of the Account.",
                        max_length=255,
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        help_text="Official legal name, if different.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique account identifier (can be auto-generated or manually set based on config).",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_index=True,
                        default="Active",
                        help_text="e.g., Active, Inactive. Configurable choices later.",
                        max_length=50,
                    ),
                ),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "primary_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Primary industry (config picklist later).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 1-10, 11-50. Configurable picklist later.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="VAT ID / Tax ID number. Branches can have their own.",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "address_category",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("business", "Business"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="residential",
                        help_text="Category of the address (Residential/Business/Other)",
                        max_length=20,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the business (if address category is Business)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gst_number",
                    models.CharField(
                        blank=True,
                        help_text="GST number for the business (if applicable)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("BILLING", "Billing"),
                            ("SHIPPING", "Shipping"),
                            ("BRANCH", "Branch Office"),
                            ("MAILING", "Mailing"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        help_text="Type of address.",
                        max_length=50,
                    ),
                ),
                ("street_1", models.CharField(max_length=255)),
                ("street_2", models.CharField(blank=True, max_length=255, null=True)),
                ("street_3", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Full name of the contact person at this address",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number for this address",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "state_province",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 3166-1 alpha-2 country code.",
                        max_length=2,
                    ),
                ),
                (
                    "is_primary_billing",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the primary billing address for the account?",
                    ),
                ),
                (
                    "is_primary_shipping",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the primary shipping address for the account?",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="The Account this address belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customers.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "ordering": ["account", "address_type"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                ("first_name", models.CharField(db_index=True, max_length=100)),
                (
                    "last_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        help_text="Primary email address. Uniqueness recommended for non-null values.",
                        max_length=254,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "secondary_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "mobile_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("work_phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        help_text="Relevant for Business/Govt contacts.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Relevant for Business/Govt contacts.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_index=True,
                        default="Active",
                        help_text="e.g., Active, Inactive, Left Company. Configurable choices later.",
                        max_length=50,
                    ),
                ),
                (
                    "email_opt_out",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates user does not want marketing emails.",
                    ),
                ),
                ("do_not_call", models.BooleanField(default=False)),
                ("sms_opt_out", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs.",
                        null=True,
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="User ID associated with this account.",
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="The single Account this Contact is primarily associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="customers.account",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(help_text="Customer name", max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique name for the customer group within this tenant (e.g., Wholesale, VIP).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("BUSINESS", "Business"),
                            ("INDIVIDUAL", "Individual"),
                            ("GOVERNMENT", "Government"),
                        ],
                        db_index=True,
                        help_text="Fundamental type of entity this group represents.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Is this group available for assignment to Accounts within this tenant?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Group",
                "verbose_name_plural": "Customer Groups",
                "ordering": ["group_name"],
                "unique_together": {("group_name",)},
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="account",
            name="customer_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Classification of the account.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="customers.customergroup",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="parent_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to parent account for hierarchy.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_accounts",
                to="customers.account",
            ),
        ),
        migrations.CreateModel(
            name="ContactAddress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        help_text="Status of the contact-address relationship.",
                        max_length=20,
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        db_column="address_id",
                        help_text="The address associated with this contact.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_addresses",
                        to="customers.address",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        db_column="contact_id",
                        help_text="The contact associated with this address.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_addresses",
                        to="customers.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Address",
                "verbose_name_plural": "Contact Addresses",
                "db_table": "customers_contact_address",
                "unique_together": {("contact", "address")},
            },
        ),
    ]
