# Generated by Django 4.2.10 on 2025-07-14 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerGroupSellingChannel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        db_index=True,
                        default="ACTIVE",
                        help_text="Status of the relationship",
                        max_length=20,
                    ),
                ),
                (
                    "customer_group",
                    models.ForeignKey(
                        help_text="Reference to the CustomerGroup",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selling_channel_relationships",
                        to="customers.customergroup",
                    ),
                ),
                (
                    "selling_channel",
                    models.ForeignKey(
                        help_text="Reference to the SellingChannel",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_group_relationships",
                        to="pricing.sellingchannel",
                    ),
                ),
            ],
            options={
                "db_table": "customer_group_selling_channel",
                "ordering": ["customer_group__group_name", "selling_channel__name"],
            },
        ),
        migrations.AddField(
            model_name="customergroup",
            name="selling_channels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Selling channels this customer group has access to",
                related_name="customer_groups",
                through="customers.CustomerGroupSellingChannel",
                to="pricing.sellingchannel",
            ),
        ),
        migrations.AddIndex(
            model_name="customergroupsellingchannel",
            index=models.Index(
                fields=["customer_group", "selling_channel", "status"],
                name="customer_gr_custome_346750_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customergroupsellingchannel",
            index=models.Index(fields=["status"], name="customer_gr_status_900a57_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="customergroupsellingchannel",
            unique_together={("customer_group", "selling_channel")},
        ),
    ]
