# Generated by Django 4.2.10 on 2025-07-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_customergroupsellingchannel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customergroupsellingchannel",
            name="segment_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Auto-generated segment name in format 'groupname-sellingchannelname'",
                max_length=255,
            ),
        ),
    ]
