# Generated by Django 4.2.10 on 2025-07-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_customergroupsellingchannel_segment_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="country",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Country of the account.",
                max_length=100,
                null=True,
            ),
        ),
    ]
