# Generated by Django 4.2.10 on 2025-07-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_account_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderAddress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "address_category",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("business", "Business"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="residential",
                        help_text="Category of the address (Residential/Business/Other)",
                        max_length=20,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the business (if address category is Business)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gst_number",
                    models.CharField(
                        blank=True,
                        help_text="GST number for the business (if applicable)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("BILLING", "Billing"),
                            ("SHIPPING", "Shipping"),
                            ("BRANCH", "Branch Office"),
                            ("MAILING", "Mailing"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        help_text="Type of address.",
                        max_length=50,
                    ),
                ),
                ("street_1", models.CharField(max_length=255)),
                ("street_2", models.CharField(blank=True, max_length=255, null=True)),
                ("street_3", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Full name of the contact person at this address",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number for this address",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "state_province",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 3166-1 alpha-2 country code.",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Address",
                "verbose_name_plural": "Order Addresses",
                "ordering": ["address_type"],
            },
        ),
    ]
