# Generated by Django 4.2.10 on 2025-07-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_orderaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderaddress",
            name="country",
            field=models.CharField(db_index=True, max_length=5),
        ),
    ]
