# Generated by Django 4.2.10 on 2025-07-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0006_alter_orderaddress_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                db_index=True, help_text="ISO 3166-1 alpha-2 country code."
            ),
        ),
        migrations.AlterField(
            model_name="orderaddress",
            name="country",
            field=models.CharField(db_index=True),
        ),
    ]
