# Generated by Django 4.2.10 on 2025-07-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0007_alter_address_country_alter_orderaddress_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderaddress",
            name="address_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
