# Generated by Django 4.2.10 on 2025-08-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0008_orderaddress_address_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customergroup",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description for this customer group.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customergroup",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Optional display name for the customer group (for UI display, i18n, etc.).",
                max_length=150,
                null=True,
            ),
        ),
    ]
