# Generated by Django 4.2.10 on 2025-07-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_account_country"),
        ("payment_method", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmethodcustomergroupsellingchannel",
            options={
                "ordering": ["payment_method__name"],
                "verbose_name": "Payment Method Channel Availability",
                "verbose_name_plural": "Payment Method Channel Availabilities",
            },
        ),
        migrations.RemoveIndex(
            model_name="banktransferdetails",
            name="idx_btd_payment_method_fk",
        ),
        migrations.RemoveIndex(
            model_name="cashchequedddetails",
            name="idx_ccdd_payment_method",
        ),
        migrations.RemoveIndex(
            model_name="cashdirectdepositdetails",
            name="idx_cddd_payment_method",
        ),
        migrations.RemoveIndex(
            model_name="cashlogisticspartnerdetails",
            name="idx_clpd_payment_method",
        ),
        migrations.RemoveIndex(
            model_name="cashofflinedetails",
            name="idx_cod_payment_method",
        ),
        migrations.RemoveIndex(
            model_name="cashposdetails",
            name="idx_cpd_payment_method",
        ),
        migrations.RemoveIndex(
            model_name="paymentgatewayonlinedetails",
            name="idx_pgod_payment_method",
        ),
        migrations.RemoveIndex(
            model_name="paymentgatewayonlinedetails",
            name="idx_pgod_gateway",
        ),
        migrations.RemoveIndex(
            model_name="paymentgatewayonlinedetails",
            name="idx_pgod_comp_fields",
        ),
        migrations.RemoveIndex(
            model_name="paymentmethodcustomergroupsellingchannel",
            name="idx_pmcgsc_payment_id",
        ),
        migrations.RemoveIndex(
            model_name="paymentmethodcustomergroupsellingchannel",
            name="idx_pmcgsc_comp_query",
        ),
        migrations.RenameField(
            model_name="banktransferdetails",
            old_name="payment_method_id",
            new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="cashchequedddetails",
            old_name="payment_method_id",
            new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="cashdirectdepositdetails",
            old_name="payment_method_id",
            new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="cashlogisticspartnerdetails",
            old_name="payment_method_id",
            new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="cashofflinedetails",
            old_name="payment_method_id",
            new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="cashposdetails",
            old_name="payment_method_id",
            new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="paymentgatewayonlinedetails",
            old_name="gateway_id",
            new_name="gateway",
        ),
        migrations.RenameField(
            model_name="paymentgatewayonlinedetails",
            old_name="payment_method_id",
            new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="paymentmethodcustomergroupsellingchannel",
            old_name="payment_method_id",
            new_name="payment_method",
        ),
        migrations.AlterUniqueTogether(
            name="paymentgatewayonlinedetails",
            unique_together={("payment_method", "gateway")},
        ),
        migrations.AlterUniqueTogether(
            name="paymentmethodcustomergroupsellingchannel",
            unique_together={("customer_group_selling_channel", "payment_method")},
        ),
        migrations.AddIndex(
            model_name="banktransferdetails",
            index=models.Index(
                fields=["payment_method"], name="idx_btd_payment_method_fk"
            ),
        ),
        migrations.AddIndex(
            model_name="cashchequedddetails",
            index=models.Index(
                fields=["payment_method"], name="idx_ccdd_payment_method"
            ),
        ),
        migrations.AddIndex(
            model_name="cashdirectdepositdetails",
            index=models.Index(
                fields=["payment_method"], name="idx_cddd_payment_method"
            ),
        ),
        migrations.AddIndex(
            model_name="cashlogisticspartnerdetails",
            index=models.Index(
                fields=["payment_method"], name="idx_clpd_payment_method"
            ),
        ),
        migrations.AddIndex(
            model_name="cashofflinedetails",
            index=models.Index(
                fields=["payment_method"], name="idx_cod_payment_method"
            ),
        ),
        migrations.AddIndex(
            model_name="cashposdetails",
            index=models.Index(
                fields=["payment_method"], name="idx_cpd_payment_method"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgatewayonlinedetails",
            index=models.Index(
                fields=["payment_method"], name="idx_pgod_payment_method"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgatewayonlinedetails",
            index=models.Index(fields=["gateway"], name="idx_pgod_gateway"),
        ),
        migrations.AddIndex(
            model_name="paymentgatewayonlinedetails",
            index=models.Index(
                fields=["payment_method", "gateway"], name="idx_pgod_comp_fields"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethodcustomergroupsellingchannel",
            index=models.Index(fields=["payment_method"], name="idx_pmcgsc_payment_id"),
        ),
        migrations.AddIndex(
            model_name="paymentmethodcustomergroupsellingchannel",
            index=models.Index(
                fields=["customer_group_selling_channel", "payment_method"],
                name="idx_pmcgsc_comp_query",
            ),
        ),
    ]
