# Generated by Django 4.2.10 on 2025-06-26 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityStage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The master display name of the stage (e.g., 'Qualification', 'Proposal Sent').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED_WON", "Closed Won"),
                            ("CLOSED_LOST", "Closed Lost"),
                        ],
                        default="OPEN",
                        help_text="The fundamental system category of the stage.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Controls if this master stage can be added to new Sales Processes.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Master Opportunity Stage",
                "verbose_name_plural": "Master Opportunity Stages",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SalesProcess",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Sales Process",
                "verbose_name_plural": "Sales Processes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SalesProcessStageLink",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "probability",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Probability (0-100) of winning at this stage *within this specific process*.",
                    ),
                ),
                (
                    "forecast_category",
                    models.CharField(
                        choices=[
                            ("PIPELINE", "Pipeline"),
                            ("BEST_CASE", "Best Case"),
                            ("COMMIT", "Commit"),
                            ("CLOSED", "Closed"),
                            ("OMITTED", "Omitted"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sales_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="opportunities.salesprocess",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="opportunities.opportunitystage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Process Stage Link",
                "verbose_name_plural": "Sales Process Stage Links",
                "ordering": ["sales_process", "order"],
                "unique_together": {("sales_process", "stage")},
            },
        ),
        migrations.AddField(
            model_name="salesprocess",
            name="stages",
            field=models.ManyToManyField(
                related_name="sales_processes",
                through="opportunities.SalesProcessStageLink",
                to="opportunities.opportunitystage",
            ),
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A descriptive name for the deal.", max_length=255
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Manually entered estimated value of the deal in the system's default currency.",
                        max_digits=19,
                    ),
                ),
                (
                    "close_date",
                    models.DateField(
                        help_text="The expected date when the deal will be won or lost."
                    ),
                ),
                (
                    "owner",
                    models.BigIntegerField(
                        help_text="User ID of the primary user for the opportunity.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="For general notes and details about the deal.",
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="The Account this deal is with.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="customers.account",
                    ),
                ),
                (
                    "primary_contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="The main point of contact for this deal.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to="customers.contact",
                    ),
                ),
                (
                    "sales_process",
                    models.ForeignKey(
                        help_text="The sales process this opportunity follows.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="opportunities.salesprocess",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        help_text="The current stage of the opportunity within its specific sales process.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="opportunities.salesprocessstagelink",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity",
                "verbose_name_plural": "Opportunities",
                "ordering": ["-created_at"],
            },
        ),
    ]
