# Generated by Django 4.2.10 on 2025-07-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityRoles",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(help_text="Role name", max_length=100)),
                (
                    "desc",
                    models.TextField(
                        blank=True, help_text="Description of the role", null=True
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="Whether this role is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Role",
                "verbose_name_plural": "Opportunity Roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(help_text="Status name", max_length=100)),
                (
                    "desc",
                    models.TextField(
                        blank=True, help_text="Description of the status", null=True
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="Whether this status is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Status",
                "verbose_name_plural": "Opportunity Statuses",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="opportunity",
            name="sales_process",
        ),
        migrations.RemoveField(
            model_name="opportunity",
            name="stage",
        ),
        migrations.AddField(
            model_name="opportunity",
            name="service_ticket_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="The ID of the related service ticket, if any.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="status",
            field=models.ForeignKey(
                blank=True,
                help_text="The current status of the opportunity.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opportunities",
                to="opportunities.opportunitystatus",
            ),
        ),
        migrations.CreateModel(
            name="OpportunityTeamMembers",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        help_text="User ID of the assigned team member."
                    ),
                ),
                (
                    "assignment_date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date when the team member was assigned to the opportunity.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "Assigned"),
                            ("UNASSIGNED", "Unassigned"),
                        ],
                        default="ASSIGNED",
                        help_text="Current assignment status of the team member.",
                        max_length=20,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        help_text="The opportunity this team member is assigned to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="The role of the team member in this opportunity.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_members",
                        to="opportunities.opportunityroles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Team Member",
                "verbose_name_plural": "Opportunity Team Members",
                "ordering": ["assignment_date"],
                "unique_together": {("opportunity", "user_id", "role")},
            },
        ),
    ]
