# Generated by Django 4.2.10 on 2025-07-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0002_opportunityroles_opportunitystatus_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesprocess",
            name="stages",
        ),
        migrations.AlterUniqueTogether(
            name="salesprocessstagelink",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="salesprocessstagelink",
            name="sales_process",
        ),
        migrations.RemoveField(
            model_name="salesprocessstagelink",
            name="stage",
        ),
        migrations.AddField(
            model_name="opportunitystatus",
            name="type",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("CLOSED_WON", "Closed Won"),
                    ("CLOSED_LOST", "Closed Lost"),
                ],
                default="OPEN",
                help_text="The fundamental system category of the stage.",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="OpportunityStage",
        ),
        migrations.DeleteModel(
            name="SalesProcess",
        ),
        migrations.DeleteModel(
            name="SalesProcessStageLink",
        ),
    ]
