# Generated by Django 4.2.10 on 2025-07-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0003_remove_salesprocess_stages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="probability",
            field=models.IntegerField(
                default=0,
                help_text="The probability of winning the opportunity (0-100).",
            ),
        ),
    ]
