# Generated by Django 4.2.10 on 2025-07-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0004_opportunity_probability"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opportunityteammembers",
            options={
                "ordering": ["assignment_start_date"],
                "verbose_name": "Opportunity Team Member",
                "verbose_name_plural": "Opportunity Team Members",
            },
        ),
        migrations.RenameField(
            model_name="opportunityteammembers",
            old_name="assignment_date",
            new_name="assignment_start_date",
        ),
        migrations.AddField(
            model_name="opportunityteammembers",
            name="assignment_end_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the team member was unassigned from the opportunity.",
                null=True,
            ),
        ),
    ]
