# Generated by Django 4.2.10 on 2025-07-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunities", "0005_alter_opportunityteammembers_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityLeadSources",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Lead source name", max_length=100),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        help_text="Description of the lead source",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="Whether this lead source is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Lead Source",
                "verbose_name_plural": "Opportunity Lead Sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityTypes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(help_text="Type name", max_length=100)),
                (
                    "desc",
                    models.TextField(
                        blank=True, help_text="Description of the type", null=True
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, help_text="Whether this type is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity Type",
                "verbose_name_plural": "Opportunity Types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="opportunity",
            name="lead_source",
            field=models.ForeignKey(
                blank=True,
                help_text="The lead source of the opportunity.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opportunities",
                to="opportunities.opportunityleadsources",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="type",
            field=models.ForeignKey(
                blank=True,
                help_text="The type of the opportunity.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opportunities",
                to="opportunities.opportunitytypes",
            ),
        ),
    ]
