# Generated by Django 4.2.10 on 2025-07-16 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_customergroupsellingchannelproduct_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customergroupsellingchannelcategory",
            table="product_category_exclusions",
        ),
        migrations.AlterModelTable(
            name="customergroupsellingchanneldivision",
            table="product_division_exclusions",
        ),
        migrations.AlterModelTable(
            name="customergroupsellingchannelproduct",
            table="product_product_exclusions",
        ),
        migrations.AlterModelTable(
            name="customergroupsellingchannelsubcategory",
            table="product_subcategory_exclusions",
        ),
    ]
