# Generated by Django 4.2.10 on 2025-07-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_account_country"),
        ("products", "0004_alter_customergroupsellingchannelcategory_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVisibility",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this product is visible to this customer group and selling channel",
                    ),
                ),
                (
                    "last_calculated",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="When this visibility record was last calculated",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this product belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_visibilities",
                        to="products.category",
                    ),
                ),
                (
                    "customer_group_selling_channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_visibility_records",
                        to="customers.customergroupsellingchannel",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        help_text="Division this product belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_visibilities",
                        to="products.division",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visibility_records",
                        to="products.product",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subcategory this product belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_visibilities",
                        to="products.subcategory",
                    ),
                ),
            ],
            options={
                "db_table": "product_visibility",
                "indexes": [
                    models.Index(
                        fields=["is_visible", "last_calculated"],
                        name="idx_visibility_status_date",
                    ),
                    models.Index(
                        fields=["category", "is_visible", "last_calculated"],
                        name="idx_category_visibility_date",
                    ),
                    models.Index(
                        fields=["division", "category", "is_visible"],
                        name="idx_division_category_visible",
                    ),
                    models.Index(
                        condition=models.Q(("subcategory__isnull", False)),
                        fields=["subcategory", "is_visible"],
                        name="idx_subcategory_visible",
                    ),
                    models.Index(
                        fields=["product", "is_visible", "last_calculated"],
                        name="idx_product_visibility_status",
                    ),
                ],
                "unique_together": {("product", "customer_group_selling_channel")},
            },
        ),
    ]
