# Generated by Django 4.2.10 on 2025-07-21 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping_zones", "0006_load_pincode_data"),
        ("products", "0005_productvisibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductZoneRestriction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.BigIntegerField(db_index=True, default=1, editable=False),
                ),
                (
                    "company_id",
                    models.BigIntegerField(
                        db_index=True,
                        default=1,
                        editable=False,
                        help_text="Company Identifier (within tenant). Default=1 for Phase 1.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.BigIntegerField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores basic custom field data as key-value pairs defined by admin settings.",
                        null=True,
                    ),
                ),
                (
                    "restriction_mode",
                    models.CharField(
                        choices=[("INCLUDE", "Include"), ("EXCLUDE", "Exclude")],
                        help_text="Whether to include or exclude this zone for the product",
                        max_length=10,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product this restriction applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_restrictions",
                        to="products.product",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        help_text="The shipping zone being included or excluded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_restrictions",
                        to="shipping_zones.shippingzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Zone Restriction",
                "verbose_name_plural": "Product Zone Restrictions",
                "db_table": "product_zone_restrictions",
                "unique_together": {("product", "zone")},
            },
        ),
    ]
