# Generated by Django 4.2.10 on 2025-08-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_productzonerestriction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity_on_hand",
            field=models.IntegerField(default=10),
        ),
    ]
